# 以下所有的 KV 填写格式要求: 1. 修改的地方需要把尖括号一并去掉；2. : 冒号后面有空格
## GitHub 部分
github_pat: <改为 GitHub PAT获取到的 Token>
github_repo_prefix: <改为 GitHub 仓库名前缀，比如 repo1,repo2,repo3,repo4, 就只填 repo>

## GitLab 部分
gitlab_repo_prefix: <改为 GitLab 仓库名前缀，比如 repo1,repo2,repo3,repo4, 就只填 repo>
gitlab_username: <改为 GitLab 用户名>
gitlab_pats:
  # 注意，下面只填仓库名数字序号，比如 repo1,repo2,repo3,repo4，就只填 1,2,3,4 即可
  1: <改为 GitLab 仓库名1 api>
  2: <改为 GitLab 仓库名2 api>
  3: <改为 GitLab 仓库名3 api>
  4: <改为 GitLab 仓库名4 api>

## CloudFlare R2 部分
r2_accounts:
  - name: <改为 R2 帐户1 名，建议用 email 方便管理>
    account_id: <改为 R2 账户1 ID>
    access_key_id: <改为 R2 账户1 访问密钥 ID>
    secret_access_key: <改为 R2 账户1 机密访问密钥>
    bucket: <改为 R2 账户1 存储桶名称>
    dir: <改为 R2 账户1 文件存放目录>
  - name: <改为 R2 帐户2 名，建议用 email 方便管理>
    account_id: <改为 R2 账户2 ID>
    access_key_id: <改为 R2 账户2 访问密钥 ID>
    secret_access_key: <改为 R2 账户2 机密访问密钥>
    bucket: <改为 R2 账户2 存储桶名称>
    dir: <改为 R2 账户2 文件存放目录>

## 备份策略
strategy: size    # 可选 [size (默认) | quantity | 指定节点]; size: 选择容量最少的仓库来存储文件; quantity: 选择文件最少的仓库来存储文件; 指定节点: 比如  pic1 或者 pic2
delete: true    # 可选 [true (默认) | false]，已复制到 GitHub 的文件，是否从 R2 删除
